"use client";

import { Suspense, useEffect, useMemo, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Home, Search, Sparkles, Store as StoreIcon, X } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { Category, StoreDetail } from "@/types";
import StoreCard from "@/components/stores/StoreCard";
import HorizontalScroller from "@/components/layout/HorizontalScroller";

const PAGE_SIZE = 20;
const validNumber = (value: string | null) => { const number = Number(value); return Number.isInteger(number) && number > 0 ? number : null; };
async function fetchStores(categoryId: number | null) { const params = new URLSearchParams({ page: "1", limit: String(PAGE_SIZE) }); if (categoryId) params.set("categoryId", String(categoryId)); const first = await apiFetch(`/stores?${params}`); if (!first.success || !Array.isArray(first.stores)) throw new Error(first.message || "تعذر تحميل المتاجر"); const pages = Math.max(1, Number(first.pagination?.totalPages) || 1); const remaining = await Promise.all(Array.from({ length: pages - 1 }, (_, index) => { const next = new URLSearchParams(params); next.set("page", String(index + 2)); return apiFetch(`/stores?${next}`); })); return [first.stores as StoreDetail[], ...remaining.map((item) => Array.isArray(item.stores) ? item.stores as StoreDetail[] : [])].flat(); }

function StoresContent() {
  const router = useRouter(); const searchParams = useSearchParams(); const [, startTransition] = useTransition();
  const categoryId = validNumber(searchParams.get("categoryId")); const query = searchParams.get("q") || ""; const filter = ["all", "featured"].includes(searchParams.get("filter") || "") ? searchParams.get("filter")! : "all";
  const [categories, setCategories] = useState<Category[]>([]); const [allStores, setAllStores] = useState<StoreDetail[]>([]); const [featuredIds, setFeaturedIds] = useState<Set<number>>(new Set()); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [searchInput, setSearchInput] = useState(query); const [reloadKey, setReloadKey] = useState(0);
  const updateUrl = (updates: Record<string, string | number | null>) => { const next = new URLSearchParams(searchParams.toString()); Object.entries(updates).forEach(([key, value]) => value === null || value === "" || (key === "filter" && value === "all") ? next.delete(key) : next.set(key, String(value))); const value = next.toString(); startTransition(() => router.push(value ? `/stores?${value}` : "/stores")); };
  useEffect(() => { setSearchInput(query); }, [query]);
  useEffect(() => { apiFetch("/categories").then((result) => { if (result.success && Array.isArray(result.categories)) setCategories(result.categories as Category[]); }); }, []);
  useEffect(() => { let cancelled = false; setLoading(true); setError(""); Promise.all([fetchStores(categoryId), apiFetch("/stores/featured?limit=50")]).then(([stores, featured]) => { if (cancelled) return; setAllStores(stores); setFeaturedIds(new Set(Array.isArray(featured.stores) ? featured.stores.map((store: StoreDetail) => store.id) : [])); }).catch((reason) => { if (!cancelled) { setAllStores([]); setError(reason.message || "تعذر تحميل المتاجر"); } }).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, [categoryId, reloadKey]);
  const visibleStores = useMemo(() => { const needle = query.trim().toLocaleLowerCase("ar"); return allStores.filter((store) => { const matchesText = !needle || [store.name, store.description, store.city, ...(store.categories || []).map((item) => item.name)].some((value) => value?.toLocaleLowerCase("ar").includes(needle)); const matchesFilter = filter === "all" || (filter === "featured" && featuredIds.has(store.id)); return matchesText && matchesFilter && store.status !== "REJECTED"; }).map((store) => ({ ...store, isFeatured: featuredIds.has(store.id), isVerified: store.status === "APPROVED" || store.isVerified })); }, [allStores, featuredIds, filter, query]);
  const selectedCategory = categories.find((item) => item.id === categoryId); const reset = () => updateUrl({ categoryId: null, q: null, filter: null }); const hasFilters = Boolean(categoryId || query || filter !== "all");
  return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:py-12">
    <nav aria-label="مسار التنقل" className="mb-7 flex items-center gap-2 text-xs text-[#80766b]"><Link href="/" className="flex items-center gap-1 hover:text-[#7d1d29]"><Home className="size-3.5" />الرئيسية</Link><span>/</span><span className="font-bold text-[#1e1b18]">المتاجر</span></nav>
    <section className="relative isolate overflow-hidden rounded-[2rem] bg-[#681822] px-6 py-8 text-white sm:px-9 sm:py-11"><div className="absolute -left-20 -top-24 -z-10 size-72 rounded-full bg-[#d29a5f]/20 blur-3xl" /><div className="absolute bottom-0 left-[18%] -z-10 h-40 w-72 rotate-[18deg] rounded-t-full border border-white/15 bg-white/5" /><div className="absolute -bottom-32 right-[12%] -z-10 size-80 rounded-full border-[28px] border-[#e4b77d]/10" /><p className="text-xs font-bold tracking-wide text-[#f4d4a2]">دليل فيورا</p><div className="mt-2 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black sm:text-4xl">{selectedCategory ? `متاجر ${selectedCategory.name}` : "متاجر تستحق الزيارة"}</h1><p className="mt-2 text-sm text-white/80">اكتشفي متاجر محلية ومنتجاتها في مكان واحد.</p></div><div className="w-fit rounded-2xl border border-white/15 bg-white/10 px-5 py-3 backdrop-blur"><span className="block text-2xl font-black text-[#f4d4a2]">{loading ? "…" : visibleStores.length}</span><span className="text-xs text-white/75">متجر ظاهر</span></div></div></section>
    <section className="mt-5 rounded-2xl bg-white p-3 ring-1 ring-[#ede5da]"><form onSubmit={(event) => { event.preventDefault(); updateUrl({ q: searchInput.trim() || null }); }} className="relative"><Search className="absolute right-4 top-1/2 size-4 -translate-y-1/2 text-[#80766b]" /><input value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="ابحثي باسم المتجر أو المدينة أو التخصص" className="w-full rounded-xl bg-[#faf7f2] py-3 pr-11 pl-11 text-sm outline-none ring-1 ring-transparent focus:ring-[#7d1d29]" />{searchInput && <button type="button" aria-label="مسح البحث" onClick={() => { setSearchInput(""); updateUrl({ q: null }); }} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#80766b]"><X className="size-4" /></button>}</form><div className="mt-3 flex gap-2 border-t border-[#ede5da] pt-3">{[{ id: "all", label: "كل المتاجر", icon: StoreIcon }, { id: "featured", label: "المميزة", icon: Sparkles }].map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => updateUrl({ filter: item.id })} className={`flex items-center gap-1.5 rounded-full px-3.5 py-2 text-xs font-bold transition ${filter === item.id ? "bg-[#1e1b18] text-white" : "bg-[#faf7f2] text-[#4a443e] hover:bg-[#f1e8dc]"}`}><Icon className="size-3.5" />{item.label}</button>; })}</div></section>
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-black text-[#1e1b18]">تسوّقي حسب القسم</h2>{categoryId && <button onClick={() => updateUrl({ categoryId: null })} className="text-xs font-bold text-[#7d1d29]">عرض الكل</button>}</div><HorizontalScroller className="cursor-grab active:cursor-grabbing"><button onClick={() => updateUrl({ categoryId: null })} className={`group flex w-20 shrink-0 snap-start flex-col items-center gap-2 ${!categoryId ? "text-[#7d1d29]" : "text-[#4a443e]"}`}><span className={`grid size-16 place-items-center rounded-2xl ${!categoryId ? "bg-[#7d1d29] text-white" : "bg-white ring-1 ring-[#ede5da]"}`}><StoreIcon className="size-6" /></span><span className="w-full truncate text-center text-[11px] font-bold">الكل</span></button>{categories.map((category) => <button key={category.id} onClick={() => updateUrl({ categoryId: category.id })} className={`group flex w-20 shrink-0 snap-start flex-col items-center gap-2 ${categoryId === category.id ? "text-[#7d1d29]" : "text-[#4a443e]"}`}><span className={`size-16 overflow-hidden rounded-2xl bg-[#f1e8dc] ring-2 transition ${categoryId === category.id ? "ring-[#7d1d29]" : "ring-transparent group-hover:ring-[#d9cdbd]"}`}>{category.imageUrl ? <img src={category.imageUrl} alt="" className="size-full object-cover" /> : <span className="grid size-full place-items-center text-lg font-black text-[#7d1d29]">{category.name.slice(0, 1)}</span>}</span><span className="w-full truncate text-center text-[11px] font-bold">{category.name}</span></button>)}</HorizontalScroller></section>
    {hasFilters && <div className="mt-4 flex items-center justify-between text-xs"><span className="text-[#80766b]">نتائجك: {visibleStores.length}</span><button onClick={reset} className="font-bold text-[#7d1d29] hover:underline">مسح التصفية</button></div>}
    <section className="mt-7" aria-live="polite">{loading ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="h-80 animate-pulse rounded-3xl bg-white ring-1 ring-[#ede5da]" />)}</div> : error ? <State title="تعذر تحميل المتاجر" description={error} action="إعادة المحاولة" onAction={() => setReloadKey((value) => value + 1)} /> : visibleStores.length ? <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{visibleStores.map((store) => <StoreCard key={store.id} store={store} />)}</div> : <State title="لا توجد متاجر مطابقة" description="غيّري خيارات البحث أو اعرضي كل المتاجر." action="عرض كل المتاجر" onAction={reset} />}</section>
  </main>;
}
function State({ title, description, action, onAction }: { title: string; description: string; action: string; onAction: () => void }) { return <div className="rounded-[2rem] bg-white px-6 py-16 text-center ring-1 ring-[#ede5da]"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#fdf0f2] text-[#7d1d29]"><StoreIcon className="size-7" /></div><h2 className="mt-4 text-lg font-black text-[#1e1b18]">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[#80766b]">{description}</p><button onClick={onAction} className="mt-6 rounded-xl bg-[#7d1d29] px-4 py-2.5 text-xs font-bold text-white">{action}</button></div>; }
export default function StoresPage() { return <Suspense fallback={<div className="py-20 text-center text-sm">جاري تحميل المتاجر…</div>}><StoresContent /></Suspense>; }
